setup.cfg

#3 Senzing 1.6.1

---

setup.cfg
src/senzing/G2Audit.py
src/senzing/G2Config.py
src/senzing/G2Diagnostic.py
src/senzing/G2Engine.py
src/senzing/G2Product.py

Senzing 1.7.0

---

setup.cfg
src/senzing/G2Audit.py
src/senzing/G2Config.py
src/senzing/G2Diagnostic.py
src/senzing/G2Engine.py
src/senzing/G2Exception.py
src/senzing/G2Product.py

Senzing 1.9.0

---

setup.cfg
src/senzing/G2Audit.py
src/senzing/G2Config.py
src/senzing/G2ConfigMgr.py
src/senzing/G2Diagnostic.py
src/senzing/G2Engine.py
src/senzing/G2Exception.py
src/senzing/G2Hasher.py
src/senzing/G2IniParams.py
src/senzing/G2Product.py
src/senzing/__init__.py
tests/test-imports.py

Senzing 1.10.0

---

CHANGELOG.md
setup.cfg

#3 Senzing 2.8.5

---

src/senzing/G2EngineFlags.py
tests/test-g2engineflags.py

#98 Add G2EngineFlags.combine_flags()

---

tests/test-enums.py

#93 Add test for large enums

---

CHANGELOG.md

#3 Add version 2.8.7

---

setup.cfg

#3 Update version

---

src/senzing/G2Config.py
src/senzing/G2ConfigMgr.py
src/senzing/G2Diagnostic.py
src/senzing/G2Engine.py
src/senzing/G2Exception.py
src/senzing/G2Hasher.py
src/senzing/G2IniParams.py
src/senzing/G2Product.py

#106 Format to PEP-8

---

src/senzing/G2Exception.py

#108 Remove Exceptions not used by SDK

---

src/senzing/G2Exception.py

Issue 94.dockter.1

---

src/senzing/G2Exception.py
tests/test-TranslateG2ModuleException.py

#112 Accept string and bytearray in TranslateG2ModuleException

---

src/senzing/G2Exception.py

#115 Add G2DatabaseConnectionLost

---

CONTRIBUTING.md
README.md
src/senzing/G2Config.py
src/senzing/G2ConfigMgr.py
src/senzing/G2Diagnostic.py
src/senzing/G2Engine.py
src/senzing/G2Hasher.py
src/senzing/G2Product.py

#114 Migrate from master to main

---

.github/CODEOWNERS
src/senzing/G2Exception.py

#120 Added __str__ method.

---

CHANGELOG.md
setup.cfg

Issue 120.dockter.2

---

src/senzing/G2Config.py
src/senzing/G2ConfigMgr.py
src/senzing/G2Diagnostic.py
src/senzing/G2Engine.py
src/senzing/G2Hasher.py
src/senzing/G2Product.py

Issue 126.dockter.1

---

src/senzing/G2Exception.py

Add additional code mapping

---

src/senzing/G2Exception.py

#131 - Add additional codes

---

CHANGELOG.md
setup.cfg

#137 Prepare for versioned release

---

src/senzing/G2Exception.py

Issue 139 - G2Exception

---

src/senzing/G2Config.py
src/senzing/G2ConfigMgr.py
src/senzing/G2Diagnostic.py
src/senzing/G2Engine.py
src/senzing/G2Hasher.py
src/senzing/G2Product.py

Issue 134 - init functions

---

CHANGELOG.md
README.md
src/senzing/G2Exception.py
tests/test-TranslateG2ModuleException.py

Issue 147.dockter.1

---

Makefile
README.md
setup.cfg

Issue 145.dockter.1

---

src/senzing/G2Engine.py

#156 Fixes for crashes on resizing buffers.

---

src/senzing/G2Engine.py

#162 Adding new API call for searching with search-profiles.

---

.pylintrc
src/senzing/G2Config.py
src/senzing/G2ConfigMgr.py
src/senzing/G2Diagnostic.py
src/senzing/G2Engine.py
src/senzing/G2Exception.py
src/senzing/G2Hasher.py
src/senzing/G2Product.py
tests/test-TranslateG2ModuleException.py

164.dockter.2

---

src/senzing/G2Engine.py

#167 Add API functions for whyRecordInEntity

---

.github/dependabot.yml
.github/workflows/add-to-project-g2-python-dependabot.yaml

Issue number: senzing-factory/build-resources#91

senzing-factory/build-resources#91 fix dependabot project status
